name: Continuous Integration

on: [push, pull_request]

jobs:
  windows-build:
    name: Windows Build
    strategy:
      matrix:
        os: [windows-2019]
        python-version: [2.7]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Install exiftool
      run: |
        curl -L http://web.mit.edu/jhawk/mnt/cgs/Image-ExifTool-6.99/html/exiftool-6.99.zip -o exiftool-6.99.zip
        powershell -nologo -noprofile -command "& { Add-Type -A 'System.IO.Compression.FileSystem'; [IO.Compression.ZipFile]::ExtractToDirectory('exiftool-6.99.zip', 'exiftool'); }"
        set PATH=%CD%\exiftool;%PATH%
        echo ::set-env name=PATH::%PATH%
        exiftool -v
      shell: cmd
