name: Continuous Integration

on: [push, pull_request]

jobs:
  windows-build:
    name: Windows Build
    strategy:
      matrix:
        os: [windows-2019]
        python-version: [2.7]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Install Poetry
      run: |
        curl -L https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py -o get-poetry.py
        python get-poetry.py --version 1.0.10
        echo "%USERPROFILE%\.poetry\bin" >> $GITHUB_PATH
      shell: cmd
    - name: Install Package Dependencies
      run: |
        call poetry help
