name: Build Unreal Engine Docset

on: [push, pull_request]

jobs:
  build-unreal-engine-docset:
    name: Build Unreal Engine Docset
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Environment Variables
      run: |
        echo "CI_UNREAL_ENGINE_VERSION=5.3" >> $GITHUB_ENV
      shell: bash
    - name: Tar
      run: |
        which tar
      shell: bash
    
