name: OpenImageIO - Artifact

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Environment Variables
      run: |
        OIIO_FAMILY=OpenImageIO
        OIIO_VERSION=Release-1.8.17
        OIIO_PACKAGE=$OIIO_FAMILY-$OIIO_VERSION
        echo ::set-env name=OIIO_FAMILY::$OIIO_FAMILY
        echo ::set-env name=OIIO_VERSION::$OIIO_VERSION
        echo ::set-env name=OIIO_PACKAGE::$OIIO_PACKAGE
    - name: Update & Install APT Package Dependencies
      run: |
        sudo apt-get update
        sudo apt-get --yes install build-essential cmake libilmbase-dev libopenexr-dev
        sudo apt-get --yes purge boost
        sudo apt-get --yes purge cmake
    - name: Build CMake
      run: | 
        wget https://github.com/Kitware/CMake/archive/v3.15.3.tar.gz -O CMake-3.15.3.tar.gz
        tar xzf CMake-3.15.3.tar.gz
        cd CMake-3.15.3
        ./bootstrap
        make
        sudo make install
    - name: Build Boost
      run: |
        wget https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz -O boost_1_70_0.tar.gz
        tar xzf boost_1_70_0.tar.gz
        cd boost_1_70_0
        sudo ln -s /usr/local/include/python3.6m /usr/local/include/python3.6
        sudo ./bootstrap.sh --with-python=$(which python3)
        sudo ./b2 install
        sudo ldconfig
    - name: Download Source
      run: |
        wget https://github.com/OpenImageIO/oiio/archive/$OIIO_VERSION.tar.gz -O $OIIO_PACKAGE.tar.gz
        mkdir $OIIO_PACKAGE
        tar -xvf $OIIO_PACKAGE.tar.gz -C $OIIO_PACKAGE --strip-components=1
    - name: Build Package
      run: |
        VIRTUAL_ENVIRONMENT=continuous-integration
        PYTHON_VERSION=3.6
        cd $OIIO_PACKAGE
        make PYTHON_VERSION=3.6
        cd..
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        chmod +x miniconda.sh
        ./miniconda.sh -b -p $HOME/miniconda
        PATH=$HOME/miniconda/bin:$PATH
        echo ::set-env name=PATH::$PATH
        conda update --yes --quiet conda
        conda create --yes --quiet -n $VIRTUAL_ENVIRONMENT python=$PYTHON_VERSION
        source activate $VIRTUAL_ENVIRONMENT
        sudo cp OpenImageIO-Release-1.8.17/dist/linux64/bin/* /usr/bin/
        sudo cp -r OpenImageIO-Release-1.8.17/dist/linux64/lib/* /usr/lib/
        sudo rm -rf /usr/lib/python3.6
        cp OpenImageIO-Release-1.8.17/dist/linux64/lib/python3.6/site-packages/OpenImageIO.so /home/runner/miniconda/envs/$VIRTUAL_ENVIRONMENT/lib/python3.6/site-packages/
        python -c "import OpenImageIO;print(OpenImageIO.VERSION)"
