name: Continuous Integration

on: [push]

jobs:
  unix-build:
    name: Unix Build
    strategy:
      matrix:
        os: [ubuntu-18.04]
        python-version: [3.6]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Test Requests
      run: |
        pip install tqdm six
        ls -l
        python test_requests.py
