name: Continuous Integration

on: [push, pull_request]

jobs:
  continuous-integration:
    name: Continuous Integration
    strategy:
      matrix:
        os: [windows-2019]
        python-version: [2.7]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Cygwin
      run: |
        echo "VIRTUAL_ENVIRONMENT_ACTIVATE=$(cygpath -u $(PWD)/bin/activate)" >> $GITHUB_ENV
      shell: bash
    - name: Environment
      run: |
        echo $VIRTUAL_ENVIRONMENT_ACTIVATE
      shell: bash
