name: Continuous Integration

on: [push, pull_request]

jobs:
  continuous-integration:
    name: Continuous Integration
    strategy:
      matrix:
        os: [windows-2019]
        python-version: [2.7]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Cygwin
      run: |
        cygpath -u "C:\foo\bar"
      shell: bash
