name: Continuous Integration

on: [push, pull_request]

jobs:
  continuous-integration:
    name: Continuous Integration
    strategy:
      matrix:
        os: [windows-2019]
        python-version: [2.7]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Install Poetry
      run: |
        curl -L https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py -o get-poetry.py
        python get-poetry.py --version 1.0.10
        echo "$USERPROFILE\\.poetry\\bin" >> $GITHUB_PATH
      shell: bash
    - name: Install Package Dependencies
      run: |
        echo $PATH
        poetry help
      shell: bash
