name: Continuous Integration

on: [push]

jobs:
  windows-build:
    name: Windows Build
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.6]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Windows - Set up Matplotlib Backend
      run: |
        mkdir %USERPROFILE%\.matplotlib
        echo backend: Agg > %USERPROFILE%\.matplotlib\matplotlibrc
    - name: Test Matplotlib
      run: |
        pip install matplotlib nose
        nosetests
