name: Build Unreal Engine Docset

on: [push, pull_request]

jobs:
  build-unreal-engine-docset:
    name: ${{ matrix.docset }}
    strategy:
      matrix:
        docset: [C++]
      fail-fast: false
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Legendary
      run: |
        pip install legendary-gl
      shell: bash
    - name: Authenticate with Epic Games
      run: |
        mkdir -p ~/.config/legendary
        echo "${{ secrets.LEGENDARY_USER_JSON }}" > ~/.config/legendary/user.json
        tail -n 3 ~/.config/legendary/user.json
        legendary auth
      shell: bash
